FROM python:3.10-alpine

WORKDIR /app

COPY . .

EXPOSE 3000

RUN apk update && apk --no-cache add openssl bash curl &&\
    chmod +x app.py &&\
    pip install -r requirements.txt
    
CMD ["/bin/sh", "-c", "AUTO_ACCESS=true PORT=3000 python3 app.py && echo 'All done!'"]
